services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - ENV=production
    ports:
      - "8000:8000"
    # env_file:
    #   - ./server/.env.production
    networks:
      - app-network
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_BASE_URL: http://localhost/api  # NOT WORK: This pulls from .env file or env var settings
    ports:
      - "3000:3000"
    # env_file:
    #   - ./client/.env.production
    networks:
      - app-network
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"  # Expose Nginx on port 80
      - "443:443"  # Expose Nginx on port 443 (for HTTPS)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - client
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
