services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ./server:/app  # Mounts local backend folder for development
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=server.settings
    # command: python manage.py runserver 0.0.0.0:8000

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - ./client:/app  # Mounts local frontend folder for development
      - /app/node_modules  # Prevent from mounting node_modules from host
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
    # command: npm run dev
