services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    environment:
      - ENV=docker # Use dockerized db for development
    volumes:
      - ./server:/app  # Mounts local backend folder for development
    ports:
      - "8000:8000"
    depends_on:
      - db
    # env_file:
    #   - ./server/.env.docker
    networks:
      - app-network
    restart: unless-stopped

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      args:
        # NEXT_PUBLIC_API_BASE_URL: ${NEXT_PUBLIC_API_BASE_URL}  # This pulls from .env file or env var settings
        NEXT_PUBLIC_API_BASE_URL: http://localhost:8000/api  # This pulls from .env file or env var settings
    volumes:
      - ./client:/app  # Mounts local frontend folder for development
      - /app/node_modules  # Prevents overwriting node_modules for development
      - /app/.next  # Prevents overwriting next.js build for development
    ports:
      - "3000:3000"
    # command: npm run dev
    # env_file:
    #   - ./client/.env.local
    networks:
      - app-network
    restart: unless-stopped

  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    env_file:
      - ./server/.env.docker
    # environment:
    #   - POSTGRES_DB=${POSTGRES_DB}
    #   - POSTGRES_USER=${POSTGRES_USER}
    #   - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    #   - POSTGRES_HOST=${POSTGRES_HOST}
    #   - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - server
      - client
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: