# Generated by Django 5.2.1 on 2025-05-26 01:05

import django.core.validators
import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title of the campaign", max_length=255
                    ),
                ),
                (
                    "landing_page_url",
                    models.URLField(
                        help_text="The URL of the landing page",
                        validators=[django.core.validators.URLValidator()],
                    ),
                ),
                (
                    "is_running",
                    models.BooleanField(
                        default=False, help_text="Whether the campaign is running"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time the campaign was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time the campaign was last updated",
                    ),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "campaign",
                "verbose_name_plural": "campaigns",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CampaignPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True,
                        help_text="Leave blank to apply this payout worldwide",
                        max_length=2,
                        null=True,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The amount of the payout",
                        max_digits=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("EUR", "Euro"), ("USD", "US Dollar")],
                        default="EUR",
                        max_length=3,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="The date and time the payout was created",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="The date and time the payout was last updated",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payouts",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "verbose_name": "campaign_payout",
                "verbose_name_plural": "campaign_payouts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["account", "is_running"], name="campaigns_c_account_d3bf89_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["title"], name="campaigns_c_title_46e46a_idx"),
        ),
        migrations.AddIndex(
            model_name="campaignpayout",
            index=models.Index(
                fields=["campaign", "is_active"], name="campaigns_c_campaig_26e41b_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignpayout",
            constraint=models.UniqueConstraint(
                condition=models.Q(("country__isnull", False)),
                fields=("campaign", "country"),
                name="unique_campaign_country_payout",
            ),
        ),
        migrations.AddConstraint(
            model_name="campaignpayout",
            constraint=models.UniqueConstraint(
                condition=models.Q(("country__isnull", True)),
                fields=("campaign",),
                name="unique_campaign_worldwide_payout",
            ),
        ),
    ]
