# Generated by Django 5.2.1 on 2025-06-01 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="campaign",
            name="campaigns_c_title_46e46a_idx",
        ),
        migrations.RemoveIndex(
            model_name="campaignpayout",
            name="campaigns_c_campaig_26e41b_idx",
        ),
        migrations.AlterField(
            model_name="campaign",
            name="account",
            field=models.ForeignKey(
                help_text="The account that owns this campaign",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="campaignpayout",
            name="campaign",
            field=models.ForeignKey(
                help_text="The campaign this payout belongs to",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payouts",
                to="campaigns.campaign",
            ),
        ),
        migrations.AlterField(
            model_name="campaignpayout",
            name="currency",
            field=models.CharField(
                choices=[("EUR", "Euro"), ("USD", "US Dollar")],
                default="EUR",
                help_text="The currency of the payout amount",
                max_length=3,
            ),
        ),
        migrations.AlterField(
            model_name="campaignpayout",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this payout is currently active"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["account", "title"], name="campaigns_c_account_83c791_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaignpayout",
            index=models.Index(
                fields=["campaign", "country"], name="campaigns_c_campaig_65baee_idx"
            ),
        ),
    ]
