name: Server side CI

on:
  push:
    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yml'
  pull_request:
    paths:
      - 'server/**'
      - '.github/workflows/server-ci.yml'

jobs:
  test:
    name: Server side Tests
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    defaults:
      run:
        working-directory: ./server

    env:
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/test_db
      POSTGRES_HOST: localhost  # Important: use localhost in CI
      POSTGRES_PORT: 5432
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      SECRET_KEY: test-secret-key-for-ci
      DEBUG: false

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run isort check
      run: isort . --check-only --diff
      continue-on-error: true

    - name: Run Black check
      run: black . --check --diff
      continue-on-error: true

    - name: Run flake8 check
      run: flake8 . --select=E9,F63,F7,F82 --count --show-source --statistics

    - name: Run Django checks
      run: |
        python manage.py check
        python manage.py makemigrations --check --dry-run

    - name: Wait for PostgreSQL
      run: |
        sudo apt-get install -y postgresql-client
        until pg_isready -h localhost -p 5432 -U postgres; do
          echo "Waiting for PostgreSQL..."
          sleep 2
        done

    - name: Run migrations
      run: python manage.py migrate

    - name: Run tests
      run: pytest
